apiVersion: apigateway.aws.upbound.io/v1beta1
kind: RestAPI
metadata:
  labels:
    upbound.io/apigateway: {{ .Values.name }}
  name: {{ .Values.name }}
spec:
  forProvider:
    description: This is my API for demonstration purposes
    name: {{ .Values.name }}
    region: {{ .Values.region }}
    tags:
{{- range $tagKey, $tagValue := .Values.tags }}
{{ $tagKey | indent 6 }}: {{ $tagValue }}
{{- end }}
