apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xapigateways.apigateway.upbound.io
spec:
  compositeTypeRef:
    apiVersion: apigateway.upbound.io/v1alpha1
    kind: XAPIGateway
  resources:
    - name: APIGateway
      base:
        apiVersion: helm.crossplane.io/v1beta1
        kind: Release
        spec:
          wait: true
          providerConfigRef:
            name: in-cluster
          rollbackLimit: 0
          forProvider:
            namespace: upbound-system
            skipCreateNamespace: true
            chart:
              name: platform-ref-apigateway-chart
              repository: oci://xpkg.upbound.io/upbound
              version: 0.1.1-9.g6dfa3a3
          connectionDetails:
            - apiVersion: apigateway.aws.upbound.io/v1beta1
              kind: RestAPI
              fieldPath: status.atProvider.arn
              toConnectionSecretKey: restapi-arn
            - apiVersion: apigateway.aws.upbound.io/v1beta1
              kind: RestAPI
              fieldPath: status.atProvider.id
              toConnectionSecretKey: restapi-id
          writeConnectionSecretToRef:
            name: apigateway
            namespace: upbound-system
      patches:
        - fromFieldPath: metadata.name
          toFieldPath: spec.forProvider.values.name
        - fromFieldPath: metadata.name
          toFieldPath: spec.connectionDetails[0].name
        - fromFieldPath: metadata.name
          toFieldPath: spec.connectionDetails[1].name
        - fromFieldPath: spec.parameters.region
          toFieldPath: spec.forProvider.values.region
        - fromFieldPath: spec.parameters.tags
          toFieldPath: spec.forProvider.values.tags
        - fromFieldPath: spec.parameters.resources
          toFieldPath: spec.forProvider.values.resources
        - type: CombineFromComposite
          combine:
            variables:
            - fromFieldPath: metadata.name
            - fromFieldPath: metadata.uid
            strategy: string
            string:
              fmt: apigateway-%s-%s
          toFieldPath: spec.writeConnectionSecretToRef.name
    - name: secret2status
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        spec:
          # Use management policy Observe to observe k8s resource,
          # but leave to third party to create, update, or delete the resource
          managementPolicy: Observe
          forProvider:
            manifest:
              apiVersion: v1
              kind: Secret
              metadata:
                namespace: upbound-system
      patches:
        - type: CombineFromComposite
          combine:
            variables:
            - fromFieldPath: metadata.name
            - fromFieldPath: metadata.uid
            strategy: string
            string:
              fmt: apigateway-%s-%s
          toFieldPath: spec.forProvider.manifest.metadata.name
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.manifest.data.restapi-arn
          toFieldPath: status.agw.restapi-arn
          transforms:
            - type: string
              string:
                type: Convert
                convert: FromBase64
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.manifest.data.restapi-id
          toFieldPath: status.agw.restapi-id
          transforms:
            - type: string
              string:
                type: Convert
                convert: FromBase64
    - name: deployment
      base:
        apiVersion: apigateway.aws.upbound.io/v1beta1
        kind: Deployment
      patches:
        - fromFieldPath: spec.parameters.region
          toFieldPath: spec.forProvider.region
        - fromFieldPath: status.agw.restapi-id
          toFieldPath: spec.forProvider.restApiId
          policy:
            fromFieldPath: Required
    - name: stage
      base:
        apiVersion: apigateway.aws.upbound.io/v1beta1
        kind: Stage
        spec:
          forProvider:
            stageName: prod
            deploymentIdSelector:
              matchControllerRef: true
      patches:
        - fromFieldPath: spec.parameters.region
          toFieldPath: spec.forProvider.region
        - fromFieldPath: spec.parameters.tags
          toFieldPath: spec.forProvider.tags
        - fromFieldPath: status.agw.restapi-id
          toFieldPath: spec.forProvider.restApiId
          policy:
            fromFieldPath: Required
    - name: domain
      base:
        apiVersion: apigateway.aws.upbound.io/v1beta1
        kind: DomainName
        spec:
          forProvider:
            endpointConfiguration:
              - types:
                - REGIONAL
      patches:
        - fromFieldPath: spec.parameters.region
          toFieldPath: spec.forProvider.region
        - fromFieldPath: spec.parameters.tags
          toFieldPath: spec.forProvider.tags
        - fromFieldPath: spec.parameters.domain.name
          toFieldPath: spec.forProvider.domainName
        - fromFieldPath: spec.parameters.domain.certificateArn
          toFieldPath: spec.forProvider.regionalCertificateArn
