apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: platform-ref-apigateway
  annotations:
    meta.crossplane.io/maintainer: Upbound <support@upbound.io>
    meta.crossplane.io/source: github.com/upbound/platform-ref-apigateway
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      This reference platform Configuration for AWS APIGateway
      is a starting point to build, run, and operate your APIGateway dynamic
      abstraction and offer a self-service capability to your internal teams.

    meta.crossplane.io/readme: |
      This reference platform Configuration for AWS APIGateway
      is a starting point to build, run, and operate your APIGateway dynamic
      abstraction and offer a self-service capability to your internal teams.
      It uses experimental(!) abstracted helm approach to reuse helm templating
      for dynamic parts of the managed resource composition. The future implementation
      of this dynamic functionality with templating capabilities is targeted to be
      based on [Composition Functions](https://docs.crossplane.io/knowledge-base/guides/composition-functions/)
      right after they mature to v1beta1.
      This Configuration uses cloud APIGateway service primitives from the [Upbound Official AWS
      Provider](https://marketplace.upbound.io/providers/upbound/provider-aws).

      To learn more checkout the [GitHub
      repo](https://github.com/upbound/platform-ref-apigateway/) that you can copy and
      customize to meet the exact needs of your organization!
spec:
  crossplane:
    version: ">=v1.7.0-0"
  dependsOn:
    - provider: xpkg.upbound.io/upbound/provider-aws
      version: ">=v0.15.0"
    - provider: xpkg.upbound.io/crossplane-contrib/provider-helm
      version: ">=v0.12.0"
    - provider: xpkg.upbound.io/crossplane-contrib/provider-kubernetes
      version: ">=v0.7.0"
